//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VorobyevP_Scooter_practice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class charging_station
    {
        public charging_station()
        {
            this.station_usage_statistics = new HashSet<station_usage_statistics>();
        }
    
        public int id_station { get; set; }
        public string address { get; set; }
        public Nullable<int> available_slots { get; set; }
    
        public virtual ICollection<station_usage_statistics> station_usage_statistics { get; set; }
    }
}
