//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VorobyevP_Scooter_practice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public clients()
        {
            this.feedback = new HashSet<feedback>();
            this.orders = new HashSet<orders>();
        }
    
        public int id_client { get; set; }
        public string client_surname { get; set; }
        public string client_name { get; set; }
        public string client_patronymic { get; set; }
        public string phone_number { get; set; }
        public Nullable<int> id_gender { get; set; }
        public string email { get; set; }
        public string address { get; set; }
    
        public virtual gender gender { get; set; }
        public virtual ICollection<feedback> feedback { get; set; }
        public virtual ICollection<orders> orders { get; set; }
    }
}
