//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VorobyevP_Scooter_practice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public int id_employee { get; set; }
        public int id_role { get; set; }
        public Nullable<int> id_gender { get; set; }
        public string emp_surname { get; set; }
        public string emp_name { get; set; }
        public string emp_patronymic { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public int id_work_schedule { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string pswd { get; set; }
    
        public virtual gender gender { get; set; }
        public virtual role role { get; set; }
        public virtual work_schedule work_schedule { get; set; }
    }
}
