//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VorobyevP_Scooter_practice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int id_feedback { get; set; }
        public int id_client { get; set; }
        public int id_scooter { get; set; }
        public int rating { get; set; }
        public string comment { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual scooters scooters { get; set; }
    }
}
