//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VorobyevP_Scooter_practice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class gender
    {
        public gender()
        {
            this.clients = new HashSet<clients>();
            this.employees = new HashSet<employees>();
        }
    
        public int id_gender { get; set; }
        public string namegender { get; set; }
    
        public virtual ICollection<clients> clients { get; set; }
        public virtual ICollection<employees> employees { get; set; }
    }
}
