//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VorobyevP_Scooter_practice.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VorobyevP_Scooter_practiceEntities : DbContext
    {
        public VorobyevP_Scooter_practiceEntities()
            : base("name=VorobyevP_Scooter_practiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<charging_station> charging_station { get; set; }
        public DbSet<clients> clients { get; set; }
        public DbSet<employees> employees { get; set; }
        public DbSet<feedback> feedback { get; set; }
        public DbSet<gender> gender { get; set; }
        public DbSet<orders> orders { get; set; }
        public DbSet<promotions> promotions { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<scooters> scooters { get; set; }
        public DbSet<station_usage_statistics> station_usage_statistics { get; set; }
        public DbSet<work_schedule> work_schedule { get; set; }
    }
}
