//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VorobyevP_Scooter_practice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int id_order { get; set; }
        public int id_client { get; set; }
        public int id_scooter { get; set; }
        public Nullable<System.DateTime> start_datetime { get; set; }
        public Nullable<System.DateTime> end_datetime { get; set; }
        public decimal total_cost { get; set; }
        public Nullable<int> id_promotion { get; set; }
        public string status { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual promotions promotions { get; set; }
        public virtual scooters scooters { get; set; }
    }
}
