//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VorobyevP_Scooter_practice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotions
    {
        public promotions()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int id_promotion { get; set; }
        public string promotionname { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public decimal discount_amount { get; set; }
    
        public virtual ICollection<orders> orders { get; set; }
    }
}
