//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VorobyevP_Scooter_practice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.employees = new HashSet<employees>();
        }
    
        public int id_role { get; set; }
        public string namerole { get; set; }
    
        public virtual ICollection<employees> employees { get; set; }
    }
}
