//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VorobyevP_Scooter_practice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class scooters
    {
        public scooters()
        {
            this.feedback = new HashSet<feedback>();
            this.orders = new HashSet<orders>();
        }
    
        public int id_scooter { get; set; }
        public string model { get; set; }
        public string manufacturer { get; set; }
        public string power { get; set; }
        public Nullable<int> max_speed { get; set; }
        public Nullable<int> weight { get; set; }
        public string load_capacity { get; set; }
        public Nullable<System.DateTime> last_maintenance_date { get; set; }
    
        public virtual ICollection<feedback> feedback { get; set; }
        public virtual ICollection<orders> orders { get; set; }
    }
}
