//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VorobyevP_Scooter_practice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_usage_statistics
    {
        public int id_statistics { get; set; }
        public int id_station { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int total_uses { get; set; }
    
        public virtual charging_station charging_station { get; set; }
    }
}
