//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VorobyevP_Scooter_practice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_schedule
    {
        public work_schedule()
        {
            this.employees = new HashSet<employees>();
        }
    
        public int id_work_schedule { get; set; }
        public System.TimeSpan shift_started { get; set; }
        public System.TimeSpan shift_end { get; set; }
    
        public virtual ICollection<employees> employees { get; set; }
    }
}
